# Generated by Django 5.1.15 on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_optional_task_due_and_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
