# Generated by Django 5.1.15 on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.FileField(blank=True, upload_to="profiles/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="language",
            field=models.CharField(choices=[("en", "English"), ("tr", "Turkish")], default="en", max_length=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(choices=[("Europe/Istanbul", "Europe/Istanbul"), ("UTC", "UTC"), ("Europe/London", "Europe/London"), ("Europe/Berlin", "Europe/Berlin"), ("America/New_York", "America/New_York")], default="Europe/Istanbul", max_length=64),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="title",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
