# Generated by Django 5.1.15 on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="default_task_view",
            field=models.CharField(choices=[("cards", "Cards"), ("list", "List")], default="cards", max_length=10),
        ),
    ]
